routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('registrations');
});
Route::get('about', function () {
    return view('about');
});
Route::resource('registrations', 'registrationsController');
Route::post('/registrations/getSites/','registrationsController@getSites')->name('registrations.getSites');
Route::get('showregistration/{id}', 'showregistrationController');
Route::resource('bandplan', 'bandplanController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/bandplan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class bandplan extends Model
{
    protected $fillable = [
        'startFreq', 'endFreq','allocation','region1FrequencyRangeFootnotes','ECAFootnotes','ECAFrequencyRangeFootnotes','harmonisationMeasure','applications','standard','notes'
    ];
}

app/registrations.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class registrations extends Model
{
    protected $fillable = [
        'startFreq', 'endFreq','measurementDate','siteID'
    ];

    public function site()
    {
        return $this->belongsTo(sites::class,'siteID', );
    }
}

app/sites.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class sites extends Model
{
    protected $fillable = [
        'name', 'country'
    ];

    public function registration()
    {
        return $this->hasMany(registrations::class,'id', 'siteID');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/bandplanController.php
<?php

namespace App\Http\Controllers;

use App\bandplan;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;

class bandplanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return
     */

    public function index(Request $request)
    {
        if(request()->ajax()) {
            $bandplan = bandplan::select('startFreq','endFreq','allocation','applications','standard','notes');

            if (!empty($request->startFreq)){
                $bandplan->where('endFreq','>',($request->startFreq));
            }
            if (!empty($request->endFreq)){
                $bandplan->where('startFreq','<',($request->endFreq));
            }

            return (new DataTables)->eloquent($bandplan)->toJson();
        }
        return view('bandplan');
    }

}

app/Http/Controllers/registrationsController.php
<?php

namespace App\Http\Controllers;

use App\sites;
use App\registrations;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;

class registrationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return
     */

    public function index(Request $request)
    {
        if(request()->ajax()) {
            $registrations = registrations::with('site');

            if (!empty($request->from_date)){
                $registrations->where('measurementDate','>=', $request->from_date);
            }
            if (!empty($request->to_date)){
                $registrations->where('measurementDate','<=', $request->to_date);
            }
            if (!empty($request->sites)){
                $registrations->whereIN('siteID', $request->sites);
            }
            if (!empty($request->startFreq)){
                $registrations->where('endFreq','>',($request->startFreq));
            }
            if (!empty($request->endFreq)){
                $registrations->where('startFreq','<',($request->endFreq));
            }

            return (new DataTables)->eloquent($registrations)->addColumn('site', function (registrations $registration) {
                return $registration->site->name;
            })->toJson();
        }
        return view('registrations');
    }
    public function getSites(Request $request){

        $search = $request->search;

        if($search == ''){
            $sites = sites::orderby('name','asc')->select('id','name')->limit(40)->get();
        }else{
            $sites = sites::orderby('name','asc')->select('id','name')->where('name', 'like', '%' .$search . '%')->limit(40)->get();
        }

        $response = array();
        foreach($sites as $site){
            $response[] = array(
                "id"=>$site->id,
                "text"=>$site->name
            );
        }

        echo json_encode($response);
        exit;
    }


}

app/Http/Controllers/showregistrationController.php
<?php

namespace App\Http\Controllers;

use App\sites;
use Illuminate\Http\Request;
use App\registrations;

class showregistrationController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function __invoke($id)
    {
        $startFreq = registrations::where('id',$id)->value('startFreq');
        $endFreq = registrations::where('id',$id)->value('endFreq');
        $dateString = registrations::where('id',$id)->value('measurementDate');
        $date = strtotime($dateString);
        $siteID = sprintf('%02d', registrations::where('id',$id)->value('siteId'));
        $siteName = sites::where('id',$siteID)->value('name');

        $day = date('d', $date);
        $month = date('m', $date);
        $year = date('y', $date);

        $spectrogramUrl =
            'data/' . $startFreq . '_'. $endFreq . '_' . $day . $month . $year .'/' .
            $startFreq . "_" . $endFreq . '_' . $day . $month . $year . '_' . $siteID . '_speco.png';
        $waterfallUrl =
            'data/' . $startFreq . '_'. $endFreq . '_' . $day . $month . $year .'/' .
            $startFreq . "_" . $endFreq . '_' . $day . $month . $year . '_' . $siteID . '_water.png';
        $spectraUrl =
            'data/' . $startFreq . '_'. $endFreq . '_' . $day . $month . $year .'/' .
            $startFreq . "_" . $endFreq . '_' . $day . $month . $year . '_' . $siteID . '_speca.png';
        $occupancyUrl =
            'data/' . $startFreq . '_'. $endFreq . '_' . $day . $month . $year .'/' .
            $startFreq . "_" . $endFreq . '_' . $day . $month . $year . '_' . $siteID . '_occup.png';

        return view('showregistration', [
            'dateString' => $dateString,
            'siteName' => $siteName,
            'startFreq' => $startFreq,
            'endFreq'=> $endFreq,
            'spectrogramUrl' => $spectrogramUrl,
            'waterfallUrl' => $waterfallUrl,
            'spectraUrl' => $spectraUrl,
            'occupancyUrl' => $occupancyUrl
        ]);
    }
}

resources/views/about.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>About</h1>
@stop

@section('content')
<div style="text-align: center;">
    This software is written by Wouter Bakker (wouter.bakker@rdi.nl) and licensed under European Union Public Licence Version 1.2 (EUPLv1.2). <br> If you have any questions about this software please contact me by email.
    The source code of this software is published on GitLab. <a href="https://gitlab.com/wouterbakker/fm22-hf-monitoring">https://gitlab.com/wouterbakker/fm22-hf-monitoring</a>. Feel free to create an issue or merge request there. <br>
    <br>
    The measurement schedule can be downloaded as csv or excel format.<br>
    <a href="schedule/FM_22_HF_schedule_2022_2026.csv">CSV download</a> <br>
    <a href="schedule/FM_22_HF_schedule_2022_2026.xlsx">Excel download</a> <br>
</div>

@stop
@section('css')

@stop

@section('js')

@stop

resources/views/bandplan.blade.php
@extends('adminlte::page')

@section('title', 'Bandplan')

@section('content_header')
    <h1>Bandplan</h1>
@stop

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-md-3">
                <h4>Frequency selection</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <label for="startFreq" class="col-2 col-form-label">Start <br>(kHz)</label>
                <input class="form-control" type="number" value="1" id="startFreq">
            </div>
            <div class="col-md-3">
                <label for="endFreq" class="col-2 col-form-label">End <br>(kHz)</label>
                <input class="form-control" type="number" value="10000000000" id="endFreq">
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12">
                <div class="box">

                    <div class="box-header">
                        @if(Session::has('message'))
                            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                        @endif
                    </div>
                    <div class="box-body">
                        <table id="bandplan" class="table table-bordered table-hover dataTable">
                            <thead>
                            <tr>
                                <th>Start frequency (kHz)</th>
                                <th>End frequency (kHz)</th>
                                <th>RR Region 1 Allocation</th>
                                <th>Application</th>
                                <th>Standard</th>
                                <th>Notes</th>

                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <div class="row">
            <div class="col-md-12">
                <div style="text-align: center;">
                    Source: <a href="https://www.efis.dk/sitecontent.jsp?sitecontent=ecatable" target="_blank">https://www.efis.dk/sitecontent.jsp?sitecontent=ecatable</a>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">

@stop

@section('js')
    {{--    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>--}}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready( function () {
            load_data();

            function load_data(startFreq = '',endFreq = '') {
                $('#bandplan').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: '{{ route("bandplan.index") }}',
                        data: {startFreq: startFreq, endFreq:endFreq}
                    },
                    columns: [
                        {data: 'startFreq', name: 'startFreq'},
                        {data: 'endFreq', name: 'endFreq'},
                        {data: 'allocation', name: 'allocation'},
                        {data: 'applications', name: 'applications'},
                        {data: 'standard', name: 'standard'},
                        {data: 'notes', name: 'notes'},
                    ]
                });
            }
            $('#filter').click(function(){

                var startFreq = $('#startFreq').val();
                var endFreq = $('#endFreq').val();

                $('#bandplan').DataTable().destroy();
                load_data(startFreq,endFreq);

            });

            $('#refresh').click(function(){
                $('#startFreq').val('1');
                $('#endFreq').val('10000000000');
                $('#bandplan').DataTable().destroy();
                load_data();
            });
            $(document).on('keypress',function(e) {
                if(e.which == 13) {
                    var startFreq = $('#startFreq').val();
                    var endFreq = $('#endFreq').val();

                    $('#bandplan').DataTable().destroy();
                    load_data(startFreq,endFreq);
                }
            });



        });

    </script>
@stop

resources/views/registrations.blade.php
@extends('adminlte::page')

@section('title', 'Registrations FM22 HF monitoring')

@section('content_header')
    <h1>Registrations</h1>
@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h4>Frequency selection</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <label for="startFreq" class="col-2 col-form-label">Start <br>(kHz)</label>
                <input class="form-control" type="number" value="1" id="startFreq">
            </div>
            <div class="col-md-3">
                <label for="endFreq" class="col-2 col-form-label">End <br>(kHz)</label>
                <input class="form-control" type="number" value="10000000000" id="endFreq">
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4>Site selection</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <select id='selSite' multiple="multiple" style="width: 258px;">
                    <option value='0'>-- Select site --</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4>Date selection</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <input class="date form-control"  type="text" id="datepickerStart" name="date" placeholder="Select start date">
            </div>
            <div class="col-md-3">
                <input class="date form-control"  type="text" id="datepickerEnd" name="date" placeholder="Select end date">
            </div>
            <div class="col-md-4">
                <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12">
                <div class="box">

                    <div class="box-header">
                        @if(Session::has('message'))
                            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                        @endif
                    </div>
                    <div class="box-body">
                        <table id="registrations" class="table table-bordered table-hover dataTable">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Start frequency (kHz)</th>
                                <th>End frequency (kHz)</th>
                                <th>Site Name</th>
                                <th>Date</th>

                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
    </div>
@stop

@section('css')

    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.standalone.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css" rel="stylesheet">

@stop

@section('js')
    {{--    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>--}}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"></script>
    <script type="text/javascript">
        $('#datepickerStart').datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd'
        });
    </script>

    <script>
        // CSRF Token
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        $(document).ready( function () {
            $('.js-example-basic-multiple').select2();

            load_data();

            function load_data(from_date = '', to_date = '', sites = '',startFreq = '',endFreq = '') {

                $("#startFreq").on('change', function () {
                    var from_date = $('#datepickerStart').val();
                    var to_date = $('#datepickerEnd').val();
                    var sites = $('#selSite').select2("val");
                    var startFreq = $('#startFreq').val();
                    var endFreq = $('#endFreq').val();

                    $('#registrations').DataTable().destroy();
                    load_data(from_date,to_date,sites,startFreq,endFreq);
                });
                $("#endFreq").on('change', function () {
                    var from_date = $('#datepickerStart').val();
                    var to_date = $('#datepickerEnd').val();
                    var sites = $('#selSite').select2("val");
                    var startFreq = $('#startFreq').val();
                    var endFreq = $('#endFreq').val();

                    $('#registrations').DataTable().destroy();
                    load_data(from_date,to_date,sites,startFreq,endFreq);
                });
                $('#registrations').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: '{{ route("registrations.index") }}',
                        data: {from_date: from_date, to_date: to_date, sites: sites, startFreq: startFreq, endFreq:endFreq}
                    },
                    columns: [
                        {data: 'id', name: 'id', render: function(data, type, full, meta) {
                                return '<a href="showregistration/'+data+'">Show registration '+ data + '</a>'}},
                        {data: 'startFreq', name: 'startFreq'},
                        {data: 'endFreq', name: 'endFreq'},
                        {data: 'site', name: 'site.name'},
                        {data: 'measurementDate', name: 'measurementDate'},
                    ]
                });
            }
            $('#filter').click(function(){
                var from_date = $('#datepickerStart').val();
                var to_date = $('#datepickerEnd').val();
                var sites = $('#selSite').select2("val");
                var startFreq = $('#startFreq').val();
                var endFreq = $('#endFreq').val();

                $('#registrations').DataTable().destroy();
                load_data(from_date,to_date,sites,startFreq,endFreq);

            });

            $('#refresh').click(function(){
                $('#datepickerStart').datepicker('setDate', null);
                $('#datepickerEnd').datepicker('setDate', null);
                $('#selSite').val(null).trigger('change');
                $('#startFreq').val('1');
                $('#endFreq').val('10000000000');
                $('#registrations').DataTable().destroy();
                load_data();
            });
            $( "#selSite" ).select2({

                ajax: {
                    url: "{{ route('registrations.getSites') }}",
                    type: "post",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            _token: CSRF_TOKEN,
                            search: params.term // search term
                        };
                    },
                    processResults: function (response) {
                        return {
                            results: response
                        };
                    },
                    cache: true

                },
                placeholder: 'Search for a measurement site',

            });
            $('#selSite').on("select2:select", function(e) {
                var from_date = $('#datepickerStart').val();
                var to_date = $('#datepickerEnd').val();
                var sites = $('#selSite').select2("val");
                var startFreq = $('#startFreq').val();
                var endFreq = $('#endFreq').val();

                $('#registrations').DataTable().destroy();
                load_data(from_date,to_date,sites,startFreq,endFreq);
            });
            $('#selSite').on("select2:unselect", function(e) {
                var from_date = $('#datepickerStart').val();
                var to_date = $('#datepickerEnd').val();
                var sites = $('#selSite').select2("val");
                var startFreq = $('#startFreq').val();
                var endFreq = $('#endFreq').val();

                $('#registrations').DataTable().destroy();
                load_data(from_date,to_date,sites,startFreq,endFreq);
            });


            $('#datepickerEnd').datepicker({
                autoclose: true,
                format: 'yyyy-mm-dd',
            }).on('changeDate',function(e) {
                var from_date = $('#datepickerStart').val();
                var to_date = $('#datepickerEnd').val();
                var sites = $('#selSite').select2("val");
                var startFreq = $('#startFreq').val();
                var endFreq = $('#endFreq').val();

                $('#registrations').DataTable().destroy();
                load_data(from_date,to_date,sites,startFreq,endFreq);
            });
            $('#datepickerStart').datepicker({
                autoclose: true,
                format: 'yyyy-mm-dd',
            }).on('changeDate',function(e) {
                var from_date = $('#datepickerStart').val();
                var to_date = $('#datepickerEnd').val();
                var sites = $('#selSite').select2("val");
                var startFreq = $('#startFreq').val();
                var endFreq = $('#endFreq').val();

                $('#registrations').DataTable().destroy();
                load_data(from_date,to_date,sites,startFreq,endFreq);
            });

            $(document).on('keypress',function(e) {
                if(e.which == 13) {
                    var from_date = $('#datepickerStart').val();
                    var to_date = $('#datepickerEnd').val();
                    var sites = $('#selSite').select2("val");
                    var startFreq = $('#startFreq').val();
                    var endFreq = $('#endFreq').val();

                    $('#registrations').DataTable().destroy();
                    load_data(from_date,to_date,sites,startFreq,endFreq);
                }
            });


        });


    </script>
@stop

resources/views/showregistration.blade.php
@extends('adminlte::page')

@section('title', 'Show registration')

@section('content_header')
    <div style="text-align: center;">
        <h1>{{$dateString}} </h1>
        <h1>{{$siteName}}</h1>
        <h1>{{$startFreq}} kHz - {{$endFreq}} kHz</h1>
    </div>

@stop

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div style="text-align: center;">
                    <h3> Spectrogram </h3>
                </div>
                <img src="{{ asset($spectrogramUrl)}}" alt="Spectrogram" width="100%">
            </div>
            <div class="col-xl-12">
                <div style="text-align: center;">
                    <h3> Bandplan </h3>
                </div>

            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="box">

                        <div class="box-header">
                            @if(Session::has('message'))
                                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                            @endif
                        </div>
                        <div class="box-body">
                            <table id="bandplan" class="table table-bordered table-hover dataTable">
                                <thead>
                                <tr>
                                    <th>Start frequency (kHz)</th>
                                    <th>End frequency (kHz)</th>
                                    <th>RR Region 1 Allocation</th>
                                    <th>Application</th>
                                    <th>Standard</th>
                                    <th>Notes</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <div class="col-xl-6">
                <div style="text-align: center;">
                    <h3> Spectra </h3>
                </div>
                <img src="{{ asset($spectraUrl)}}" alt="Spectrogram" width="100%">
            </div>
            <div class="col-xl-6">
                <div style="text-align: center;">
                    <h3> Occupancy </h3>
                </div>
                <img src="{{ asset($occupancyUrl)}}" alt="Waterfall" width="100%">
            </div>
            <div class="col-xl-6">
                <div style="text-align: center;">
                    <h3> Waterfall </h3>
                </div>
                <img src="{{ asset($waterfallUrl)}}" alt="Waterfall" width="100%">
            </div>
        </div>
    </div>

@stop

@section('css')
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
@stop

@section('js')
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready( function () {

            load_data("{{$startFreq}}" ,"{{$endFreq}}" );

            function load_data(startFreq = '' ,endFreq =  '') {
                $('#bandplan').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: '{{ route("bandplan.index") }}',
                        data: {startFreq: startFreq, endFreq:endFreq}
                    },
                    columns: [
                        {data: 'startFreq', name: 'startFreq'},
                        {data: 'endFreq', name: 'endFreq'},
                        {data: 'allocation', name: 'allocation'},
                        {data: 'applications', name: 'applications'},
                        {data: 'standard', name: 'standard'},
                        {data: 'notes', name: 'notes'},
                    ]
                });
            }
        });

    </script>
@stop